spring:
  application:
    name: server-eureka
server:
  port: 10000
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    
    