spring:
  cloud:
    config:
      server:
        git:
#          searchPaths: config
          uri: https://github.com/jiaorpeng/blogConfig.git
          username: jiaorpeng
          password: rempop.3469
      label: master
  application:
    name: server-config
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10000/eureka/